name: Secrets

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty secrets for repository
        run: |
          echo "$i"
          curl \
          -X PUT \
          --header 'authorization: token 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' \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Akeem35/demo/actions/secrets/SUPER_SECRET \
          -d '{"encrypted_value":"encrypted_value"}'
          # -u Akeem35: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 \
