name: Secrets

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty secrets for repository
        run: |
          declare -a env_vars=(AWS_KEY AWS_SECRET GHA_PAT IMG_S3_ACCESS_KEY IMG_S3_BUCKET IMG_S3_REGION IMG_S3_SECRET_KEY JWT_API_KEY, SECRET_KEY SPRING_DATASOURCE_PASSWORD SPRING_DATASOURCE_URL SPRING_DATASOURCE_USERNAME)
          for i in "${env_vars[@]}"
          do
            echo "$i"
            curl \
            -u akeem35:${{ secrets.PAT_TOKEN }} \
            -X PUT \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            https://api.github.com/repos/akeem35/template_maven_api/actions/secrets/$i \
            -d '{"encrypted_value":""}'
          done
