name: Secrets

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create empty secrets for repository
        run: |
          declare -a env_vars=(AWS_KEY AWS_SECRET GHA_PAT IMG_S3_ACCESS_KEY IMG_S3_BUCKET IMG_S3_REGION IMG_S3_SECRET_KEY JWT_API_KEY, SECRET_KEY SPRING_DATASOURCE_PASSWORD SPRING_DATASOURCE_URL SPRING_DATASOURCE_USERNAME)
          for i in "${env_vars[@]}"
          do
            echo "$i"
            curl \
            -X PUT \
            -u "Akeem35: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" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/akeem35/demo/actions/secrets/$i \
            -d '{"encripted_value":""}'
          done
