name: Secrets

on: 
  push:
    paths:
      - .github/workflows/secrets.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty secrets for repository
        run: |
          curl -H 'Authorization: bearer ${{ github.token }}' -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Akeem35/demo/actions/secrets
