name: Secrets

on: 
  push:
    paths:
      - .github/workflows/secrets.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty secrets for repository
        run: |
          curl \
          -X PUT \
          --header "Authorization: token ${PAT_TOKEN}"
          -H "Accept: application/vnd.github.v3+json" \
          --url https://api.github.com/repos/Akeem35/demo/actions/secrets/SUPER_SECRET 
          # -u Akeem35:$PAT_TOKEN \
