name: Secrets

on: 
  push:
    paths:
      - .github/workflows/secrets.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create empty secrets for repository
        run: |
          curl \
          -X PUT \
          -u "Akeem35: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" \
          -H "Accept: application/vnd.github.v3+json" \
          --url https://api.github.com/repos/Akeem35/demo/actions/secrets/SUPER_SECRET \
          -d '{"encrypted_value":"encrypted_value"}'
          # -u Akeem35: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 \
